-- Screenshot 4 insertion queries
insert into game_media (game_id, media_url, media_type) values (1, 'assets/images/Age of Wonders 4/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (2, 'assets/images/Among Us/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (3, 'assets/images/Assetto Corsa/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (4, 'assets/images/Battlefield 6/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (5, 'assets/images/Blood Fresh Supply/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (6, 'assets/images/Borderlands 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (7, 'assets/images/Celeste/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (8, 'assets/images/Counter-Strike 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (9, 'assets/images/Cyberpunk 2077/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (10, 'assets/images/Dead by Daylight/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (11, 'assets/images/Deus Ex Mankind Divided/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (12, 'assets/images/Don''t Starve/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (13, 'assets/images/Dota 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (14, 'assets/images/Elden Ring/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (15, 'assets/images/Euro Tuck Simulator 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (16, 'assets/images/Fallout New Vegas/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (17, 'assets/images/Final Fantasy VII Rebirth/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (18, 'assets/images/Hollow Knight/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (19, 'assets/images/Left 4 Dead 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (20, 'assets/images/Phasmophobia/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (21, 'assets/images/Portal 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (22, 'assets/images/PUBG BATTLEGROUNDS/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (23, 'assets/images/Resident Evil Village/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (24, 'assets/images/RUST/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (25, 'assets/images/Sid Meier''s Civilization VI/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (26, 'assets/images/Stardew Valley/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (27, 'assets/images/Terraria/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (28, 'assets/images/The Witcher 3 Wild Hunt/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (29, 'assets/images/Trailmakerls/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (30, 'assets/images/Vampire Survivors/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (31, 'assets/images/World Of Warships/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (32, 'assets/images/Worms W.M.D/4.jpg', 'screenshot');
