-- Screenshot 4 insertion queries
insert into game_media (game_id, media_url, media_type) values (1, 'assets/imges/Age of Wonders 4/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (2, 'assets/imges/Among Us/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (3, 'assets/imges/Assetto Corsa/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (4, 'assets/imges/Battlefield 6/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (5, 'assets/imges/Blood Fresh Supply/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (6, 'assets/imges/Borderlands 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (7, 'assets/imges/Celeste/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (8, 'assets/imges/Counter-Strike 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (9, 'assets/imges/Cyberpunk 2077/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (10, 'assets/imges/Dead by Daylight/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (11, 'assets/imges/Deus Ex Mankind Divided/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (12, 'assets/imges/Don''t Starve/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (13, 'assets/imges/Dota 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (14, 'assets/imges/Elden Ring/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (15, 'assets/imges/Euro Tuck Simulator 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (16, 'assets/imges/Fallout New Vegas/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (17, 'assets/imges/Final Fantasy VII Rebirth/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (18, 'assets/imges/Hollow Knight/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (19, 'assets/imges/Left 4 Dead 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (20, 'assets/imges/Phasmophobia/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (21, 'assets/imges/Portal 2/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (22, 'assets/imges/PUBG BATTLEGROUNDS/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (23, 'assets/imges/Resident Evil Village/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (24, 'assets/imges/RUST/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (25, 'assets/imges/Sid Meier''s Civilization VI/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (26, 'assets/imges/Stardew Valley/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (27, 'assets/imges/Terraria/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (28, 'assets/imges/The Witcher 3 Wild Hunt/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (29, 'assets/imges/Trailmakerls/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (30, 'assets/imges/Vampire Survivors/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (31, 'assets/imges/World Of Warships/4.jpg', 'screenshot');
insert into game_media (game_id, media_url, media_type) values (32, 'assets/imges/Worms W.M.D/4.jpg', 'screenshot');
